rappers = ['Kendrick Lamar',
          'J Cole',
          'Kanye West',
          'Jay-Z',
          'The Weeknd',
          'Eminem',
          'Lil Wayne',
          'Drake',
          'Post Malone',
          'Wiz Khalifa',
          'Travis Scott',
          'Playboi Carti',
          'A$AP Rocky',
          '21 Savage',
          'Lil Uzi',
          'Kodak Black',
          'NLE Choppa',
          'Chief Keef',
          'Lil Durk',
          'Trippie Redd',
          'Future',
          'Polo G',
          'DaBaby',
          'Kid Cudi',
          'Lil Tjay',
          'Gunna',
          'Chris Brown',
          'A Boogie',
          'Yeat',
          'Lil Baby',
          'Pop Smoke',
          'Juice Wrld']
